#!/bin/bash

rm /tmp/total
clear && for i in `ls input/*.txt`; do echo $i; node script $i output/`basename $i`.out | egrep "totalScore:" | sed "s/{ totalScore: //g" | sed "s/ }//g" | tee -a /tmp/total; done

echo "-----------------------------"

echo "$(tr -s '\n' '+' < /tmp/total|sed 's/.$//')" | bc

